Repository AcademySoftwareFoundation/OpenImageIO, pull requests merged in 2024-09, with the labels that each got.

#4448 fix(raw) check for nullptr in raw input plugin
  src/raw.imageio/rawinput.cpp
Labels: bug, Dev Days, devdays24

#4451 fix (iv): iv shows constant brown and GL error messages on start-up.
  src/iv/ivgl.cpp
Labels: Dev Days, devdays24

#4446 Initialize m_pfm_flip before use to avoid UB.
  src/pnm.imageio/pnminput.cpp
Labels: bug, file formats, Dev Days, devdays24

#4457 [ivgl] Initialize variables before we use them.
  src/iv/ivgl.cpp
Labels: bug, iv, Dev Days, devdays24

#4456 docs:imageinput-errorchecking
  src/doc/imageinput.rst
  testsuite/docs-examples-cpp/src/docs-examples-imageinput.cpp
  testsuite/docs-examples-python/src/docs-examples-imageinput.py
Labels: build / testing / port / CI, docs, Dev Days, devdays24

#4460 docs: convert to test for ImageBufAlgo Partial Image Arithmetic
  src/doc/imagebufalgo.rst
  testsuite/docs-examples-cpp/ref/out-arm.txt
  testsuite/docs-examples-cpp/ref/out.txt
  testsuite/docs-examples-cpp/run.py
  testsuite/docs-examples-cpp/src/docs-examples-imagebufalgo.cpp
  testsuite/docs-examples-python/ref/out-arm.txt
  testsuite/docs-examples-python/ref/out.txt
  testsuite/docs-examples-python/run.py
  testsuite/docs-examples-python/src/docs-examples-imagebufalgo.py
Labels: build / testing / port / CI, docs, Dev Days, devdays24

#4452 Added check_open for PNG, JPEG, and EXR readers
  src/jpeg.imageio/jpeginput.cpp
  src/openexr.imageio/exrinput.cpp
  src/png.imageio/pnginput.cpp
Labels: internals, Dev Days, devdays24

#4442 api: remove redundant ImageSpec from ImageCache (issue #4436)
  src/iconvert/iconvert.cpp
  src/include/OpenImageIO/imagecache.h
  src/include/OpenImageIO/texture.h
  src/libOpenImageIO/imagebuf.cpp
  src/libOpenImageIO/imagecache_test.cpp
  src/libOpenImageIO/imagespeed_test.cpp
  src/libtexture/imagecache.cpp
  src/libtexture/imagecache_pvt.h
  src/libtexture/texture_pvt.h
  src/libtexture/texturesys.cpp
  src/oiiotool/imagerec.cpp
  src/python/py_imagecache.cpp
  src/testtex/testtex.cpp
Labels: texture / image cache, help wanted, Dev Days, devdays24

#4443 feat: add iv data and display windows overlay
  src/iv/imageviewer.cpp
  src/iv/imageviewer.h
  src/iv/ivgl.cpp
  src/iv/ivgl.h
Labels: iv, Dev Days, devdays24

#4454 feat(raw): raw reader - exposing max_raw_memory_mb
  src/doc/builtinplugins.rst
  src/raw.imageio/rawinput.cpp
Labels: file formats, Dev Days, devdays24
