Repository AcademySoftwareFoundation/OpenImageIO, pull requests merged in 2025-08, with the labels that each got.

#4846 ci: Update ABI check standard
  .github/workflows/ci.yml
Labels: build / testing / port / CI

#4844 build: C++23 support
  .github/workflows/ci.yml
  INSTALL.md
  src/iconvert/iconvert.cpp
  src/idiff/idiff.cpp
  src/iinfo/iinfo.cpp
  src/include/OpenImageIO/platform.h
  src/libOpenImageIO/exif.cpp
  src/libOpenImageIO/formatspec.cpp
  src/libOpenImageIO/imagebufalgo_test.cpp
  src/libOpenImageIO/imageio.cpp
  src/libOpenImageIO/imagespeed_test.cpp
  src/libOpenImageIO/maketexture.cpp
  src/libOpenImageIO/printinfo.cpp
  src/libtexture/imagecache.cpp
  src/libtexture/imagecache_memory_print.h
  src/libtexture/texturesys.cpp
  src/libutil/CMakeLists.txt
  src/libutil/benchmark.cpp
  src/oiiotool/diff.cpp
  src/oiiotool/expressions.cpp
  src/oiiotool/oiiotool.cpp
  src/oiiotool/printinfo.cpp
  src/rla.imageio/rlainput.cpp
  src/term.imageio/termoutput.cpp
Labels: build / testing / port / CI

#4848 docs: fix typo
  src/doc/oiiotool.rst
Labels: docs

#4856 ci: Add a VFX Platform 2026 CI job
  .github/workflows/ci.yml
  src/build-scripts/build_pybind11.bash
  src/cmake/build_pybind11.cmake
Labels: build / testing / port / CI

#4857 build: fix build on NetBSD
  src/include/OpenImageIO/strutil.h
  src/include/OpenImageIO/typedesc.h
  src/libOpenImageIO/imagebufalgo_compare.cpp
  src/libOpenImageIO/maketexture.cpp
  src/libOpenImageIO/printinfo.cpp
  src/libtexture/environment.cpp
  src/libutil/fmath_test.cpp
  src/libutil/strutil.cpp
  src/oiiotool/printinfo.cpp
  src/testtex/testtex.cpp
Labels: build / testing / port / CI

#4859 ci: Lock down to ci-oiio container with correct llvm components
  .github/workflows/ci.yml
Labels: build / testing / port / CI

#4865 deps: Raise OpenColorIO minimum to 2.3
  .github/workflows/ci.yml
  CHANGES.md
  INSTALL.md
  src/cmake/externalpackages.cmake
  src/libOpenImageIO/color_ocio.cpp
Labels: build / testing / port / CI

#4867 build: Some more minor wheel workflow changes after the py 3.9 bump
  .github/workflows/wheel.yml
  pyproject.toml
Labels: build / testing / port / CI, python

#4870 build: ffmpeg 8 support
  INSTALL.md
  src/cmake/modules/FindFFmpeg.cmake
Labels: build / testing / port / CI
