Repository AcademySoftwareFoundation/OpenImageIO, pull requests merged in 2025-05, with the labels that each got.

#4726 refactor: Rearrange initialize_cuda() for better err check, no warn
  src/libOpenImageIO/oiio_gpu.cpp
Labels: build / testing / port / CI

#4723 fmath.h: add span-based bit_unpack() utility
  src/include/OpenImageIO/fmath.h
  src/libutil/fmath_test.cpp
Labels: core APIs

#4737 int: Address safety warnings in pvt::append_tiff_dir_entry
  src/libOpenImageIO/exif.cpp
Labels: internals

#4731 ci: save time by not checking out entire project history
  .github/workflows/build-steps.yml
  .github/workflows/ci.yml
  .github/workflows/release-sign.yml
  .github/workflows/scorecard.yml
  .github/workflows/wheel.yml
Labels: build / testing / port / CI

#4730 build: fix fmt throwing behavior warnings
  src/include/OpenImageIO/detail/fmt.h
  src/libutil/strutil.cpp
Labels: build / testing / port / CI

#4736 docs: Online docs improvements, mostly formatting
  src/doc/Doxyfile
  src/doc/requirements.txt
  src/doc/texturesys.rst
  src/include/OpenImageIO/image_span.h
  src/include/OpenImageIO/span.h
Labels: docs

#4708 oiiotool: -i:native=1, fix --native behavior, fix convert datatype
  src/doc/oiiotool.rst
  src/oiiotool/imagerec.cpp
  src/oiiotool/oiiotool.cpp
Labels: oiiotool

#4673 Improved IFF support reading and writing z buffers
  src/iff.imageio/CMakeLists.txt
  src/iff.imageio/iff_pvt.h
  src/iff.imageio/iffinput.cpp
  src/iff.imageio/iffoutput.cpp
  src/iff.imageio/noproxy-iff_pvt.cpp
  src/iff.imageio/noproxy-iff_pvt.h
  src/iff.imageio/noproxy-iffinput.cpp
  src/iff.imageio/noproxy-iffoutput.cpp
Labels: enhancement, file formats

#4727 api!: add image_span versions of ImageOutput methods
  CMakeLists.txt
  src/include/OpenImageIO/image_span.h
  src/include/OpenImageIO/imageio.h
  src/include/OpenImageIO/span.h
  src/include/OpenImageIO/typedesc.h
  src/include/imageio_pvt.h
  src/libOpenImageIO/image_span_test.cpp
  src/libOpenImageIO/imageio.cpp
  src/libOpenImageIO/imageoutput.cpp
  src/libutil/typedesc_test.cpp
  testsuite/docs-examples-cpp/src/docs-examples-imageoutput.cpp
Labels: core APIs, roadmap, strategic

#4753 feat(python): _repr_png_ implementation for ImageBuf
  src/doc/figures/imagebuf-notebook-demo.png
  src/doc/pythonbindings.rst
  src/python/py_imagebuf.cpp
  testsuite/python-imagebuf/ref/invalid_repr_png.png
  testsuite/python-imagebuf/ref/valid_repr_png.png
  testsuite/python-imagebuf/run.py
  testsuite/python-imagebuf/src/AllHalfValues.exr
  testsuite/python-imagebuf/src/test_imagebuf.py
Labels: feature request, python, Dev Days, devdays25

#4758 build: fix failed test with old fmt
  src/include/OpenImageIO/typedesc.h
Labels: bug, internals, build / testing / port / CI

#4750 fix: ImageInput/ImageOutput did not set per-file threads correctly
  src/libOpenImageIO/imageinput.cpp
  src/libOpenImageIO/imageoutput.cpp
Labels: bug, core APIs

#4748 api!: add image_span versions of ImageInput methods
  CMakeLists.txt
  src/doc/imageoutput.rst
  src/include/OpenImageIO/imageio.h
  src/libOpenImageIO/imageinput.cpp
  testsuite/docs-examples-cpp/ref/out-arm.txt
  testsuite/docs-examples-cpp/ref/out.txt
  testsuite/docs-examples-cpp/ref/tiles.tif
  testsuite/docs-examples-cpp/run.py
  testsuite/docs-examples-cpp/src/docs-examples-imageinput.cpp
  testsuite/docs-examples-cpp/src/docs-examples-imageoutput.cpp
  testsuite/docs-examples-python/ref/out-arm.txt
  testsuite/docs-examples-python/ref/out.txt
  testsuite/docs-examples-python/ref/tiles.tif
  testsuite/docs-examples-python/run.py
  testsuite/docs-examples-python/src/docs-examples-imageoutput.py
Labels: core APIs, roadmap, strategic

#4762 feat(oiiotool): Added create-dir cmd arg to create dir if it doesn't exist
  src/doc/oiiotool.rst
  src/include/OpenImageIO/filesystem.h
  src/libutil/filesystem.cpp
  src/oiiotool/oiiotool.cpp
  src/oiiotool/oiiotool.h
  testsuite/oiiotool/ref/out.txt
  testsuite/oiiotool/run.py
Labels: feature request, oiiotool, Dev Days, devdays25

#4763 feat(oiiotool): eraseattrib_fromfile
  src/doc/oiiotool.rst
  src/oiiotool/oiiotool.cpp
  testsuite/oiiotool-attribs/ref/out-jpeg9d.txt
  testsuite/oiiotool-attribs/ref/out.txt
  testsuite/oiiotool-attribs/run.py
  testsuite/oiiotool-attribs/src/regex_list.txt
Labels: enhancement, oiiotool, Dev Days, devdays25

#4749 ci: Add Linux ARM test
  .github/workflows/ci.yml
  testsuite/docs-examples-cpp/ref/out-linuxarm.txt
  testsuite/docs-examples-python/ref/out-linuxarm.txt
  testsuite/psd/ref/out-linuxarm.txt
  testsuite/psd/run.py
  testsuite/texture-interp-closest/run.py
  testsuite/tiff-depths/ref/out-linuxarm.txt
Labels: build / testing / port / CI

#4757 fix(exr): not honoring 'missingcolor' for scanline files
  src/openexr.imageio/exr_pvt.h
  src/openexr.imageio/exrinput.cpp
  src/openexr.imageio/exrinput_c.cpp
Labels: bug, file formats
