Repository AcademySoftwareFoundation/OpenImageIO, pull requests merged in 2025-02, with the labels that each got.

#4612 docs: Argparse documentation/comments typos
  src/include/OpenImageIO/argparse.h
Labels: docs

#4630 fix(ImageBuf): Fix bug in ImageBuf construction from ptr + neg strides
  src/libOpenImageIO/imagebuf.cpp
  src/libOpenImageIO/imagebuf_test.cpp
Labels: bug, image processing

#4610 feat(oiiotool): oiiotool new expression eval tokens IS_CONSTANT, IS_BLACK
  src/doc/oiiotool.rst
  src/oiiotool/expressions.cpp
  testsuite/oiiotool-control/ref/out.txt
  testsuite/oiiotool-control/run.py
Labels: enhancement, oiiotool

#4633 build: fix recently broken rpath to restore python wheel building
  .github/workflows/wheel.yml
  src/cmake/compiler.cmake
Labels: bug, build / testing / port / CI, python

#4625 fix(ico): More robust to corrupted ICO files
  src/ico.imageio/icoinput.cpp
  testsuite/ico/ref/out.txt
  testsuite/ico/run.py
  testsuite/ico/src/bad1.ico
Labels: bug, file formats

#4624 fix(rla): More robust to corrupted RLA files that could overrun buffers
  src/rla.imageio/rlainput.cpp
  testsuite/rla/ref/out.txt
  testsuite/rla/run.py
  testsuite/rla/src/crash-1.rla
Labels: bug, file formats
