Repository AcademySoftwareFoundation/OpenImageIO, pull requests merged in 2025-07, with the labels that each got.

#4814 api: image_span-ify ImageBuf
  src/doc/imagebuf.rst
  src/include/OpenImageIO/image_span.h
  src/include/OpenImageIO/imagebuf.h
  src/libOpenImageIO/imagebuf.cpp
  src/libOpenImageIO/imageoutput.cpp
Labels: core APIs, roadmap

#4831 build: For python stub generation, lock pybind11
  pyproject.toml
Labels: build / testing / port / CI, python

#4828 ci: Bump 'latest releases' tests to use pybind11 3.0.0
  .github/workflows/ci.yml
  INSTALL.md
Labels: build / testing / port / CI, python

#4807 iv: Add min/max/avg and sizing to pixel closeup view
  src/iv/imageviewer.cpp
  src/iv/imageviewer.h
  src/iv/ivgl.cpp
  src/iv/ivgl.h
  src/iv/ivpref.cpp
Labels: iv

#4837 ffmpeg: Replace deprecated and soon removed avcodec_close with avcodec_free_context in ffmpeg plugin.
  src/ffmpeg.imageio/ffmpeginput.cpp
Labels: file formats, build / testing / port / CI
